### ISSUE TITLE
Can't set "Mail to Admin" as error follows up

### ISSUE THREAD

**Issue by dsg1-wolf** [nitsan-technologies/ns_news_comments#34]
Hi all!

For some odd reason, whenever I set
`plugin.tx_nsnewscomments.settings.notification.siteadmin.sendMailToAdmin = 0`

I get the following alert and I was wondering, if there's anything I could do about it:

> parsererror SyntaxError: Unexpected token O in JSON at position 0

The error persists independently of me setting it via checkbox in the extension's constants or manually in the template's "contants" field.

TYPO3-Version: 9.5.21
Extension-Version: 4.2.0

Any help would be appreciated.

Regards
Tom

**Comment by nitsan-technologies** [comment]
Hi @dsg1-wolf 

Thanks for your feedback.

This kind of issue normally found when **routeEnhancers** not configured properly or in your site some confliction found on jquery.

For the routeEnhancers, You can add below code to fix it.

```
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: /
    index: ''
    map:
      -- your code --
      nsnewscomment: 99

```
Please check both the possibility, and if still the issue is not resolved, give us more details.

Thank you!
